apiVersion: v1
kind: Service
metadata:
  name: hello-{{ .Release.Name }}-service
spec:
  type: ClusterIP
  selector:
    app: hello-{{ .Values.Environment }}
  ports:
    - protocol: TCP
      port: {{ .Values.Ports.HelloClusterPort }}
      targetPort: {{ .Values.Ports.HelloPodPort }}

