apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress-service
  #namespace: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - pathType: ImplementationSpecific
            path: /hello/?(.*)
            backend:
              service:
                name: hello-{{ .Release.Name }}-service
                port:
                  number: {{ .Values.Ports.HelloClusterPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: kubernetes-dashboard-ingress
  namespace: kube-system
spec:
  ingressClassName: public
  tls:
  - hosts:
    - test2.housepadi.ng
    secretName: tls-example
  rules:
  - host: test2.housepadi.ng
    http:
      paths:
      - backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443
        path: /dashboard(/|$)(.*)
        pathType: ImplementationSpecific
